/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "filament.exports.download": [
        {
            "name": "export",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.imports.failed-rows.download": [
        {
            "name": "import",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.admin.auth.login": [],
    "filament.admin.auth.logout": [],
    "filament.admin.pages.dashboard": [],
    "filament.admin.resources.banners.index": [],
    "filament.admin.resources.categories.index": [],
    "filament.admin.resources.categories.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.categories.create": [],
    "filament.admin.resources.categories.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.emails.index": [],
    "filament.admin.resources.emails.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.images.index": [],
    "filament.admin.resources.images.create": [],
    "filament.admin.resources.images.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.products.index": [],
    "filament.admin.resources.products.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.products.create": [],
    "filament.admin.resources.products.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.promotions.index": [],
    "filament.admin.resources.promotions.create": [],
    "filament.admin.resources.promotions.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.promotions.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.quotations.index": [],
    "filament.admin.resources.quotations.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.settings.index": [],
    "livewire.update": [],
    "livewire.upload-file": [],
    "livewire.preview-file": [
        {
            "name": "filename",
            "required": true
        }
    ],
    "sitemap.index": [],
    "cache-clear.index": [],
    "api.contact": [],
    "api.quote": [],
    "home.index": [],
    "cart.index": [],
    "favorites.index": [],
    "cart.verify": [],
    "search.index": [
        {
            "name": "search",
            "required": false
        }
    ],
    "promotion.index": [
        {
            "name": "slug",
            "required": true
        }
    ],
    "category.index": [
        {
            "name": "categorySlug",
            "required": true
        }
    ],
    "product.detail": [
        {
            "name": "categorySlug",
            "required": true
        },
        {
            "name": "productSlug",
            "required": true
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
